In [49]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [50]:
trial_data_list={"DATA":["ABC DEF IJK PQR","PQR KLM OPQ","LMN PQR XYZ ABC DEF PQR ABC"]}

In [51]:
data=pd.DataFrame(trial_data_list)

In [52]:
data['DATA']=data['DATA'].str.lower()

In [53]:
data

DATA
0              abc def ijk pqr
1                  pqr klm opq
2  lmn pqr xyz abc def pqr abc

In [54]:
vectorizer=CountVectorizer()
vectorized_data=vectorizer.fit_transform(data['DATA'])
all_words=vectorizer.get_feature_names()

In [55]:
all_words

['abc', 'def', 'ijk', 'klm', 'lmn', 'opq', 'pqr', 'xyz']

In [56]:
data_matrix=np.zeros((len(all_words),len(all_words)))

In [57]:
print(data_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
word_position_dict={}
for i in range(len(all_words)):
    word_position_dict.update({all_words[i]:i})

In [59]:
word_position_dict

{'abc': 0,
 'def': 1,
 'ijk': 2,
 'klm': 3,
 'lmn': 4,
 'opq': 5,
 'pqr': 6,
 'xyz': 7}

In [60]:
window_size=2
count=0
total_count=0
for row_word in all_words:
#     print("row_word",row_word)
    for colum_word in all_words:
        total_count=0
        temp_count=0
        if row_word == colum_word:
            continue
        else :

            for sentence in data['DATA']:
                count=0
                
#                 for word in range(0,len(sentence.split())):

                if (row_word in sentence) and (colum_word in sentence):
                    print("row word",row_word)
                    print("colum_word",colum_word)
                    
                    split_sentence=sentence.split()
#                         row_pos=split_sentence.index(row_word)
                    print(split_sentence)
                    match_pos=[n for n,x in enumerate(split_sentence) if x==row_word]
                    print("match_position",match_pos)
                    for row_pos in match_pos:
                        found_index_pos=[n for n,x in enumerate(split_sentence) if x==colum_word]
                        distance_from_word=(np.absolute(row_pos-np.array(found_index_pos))<=window_size)
                        count=sum(distance_from_word.flatten())
                        print("count",count)
                        temp_count=temp_count+count
                        print("temp_count",temp_count)
                    print("-------------------------------------")

        total_count=total_count+temp_count
        if (row_word in sentence) and (colum_word in sentence): 
            print("total count",total_count)
            
        row_index=all_words.index(row_word)
        col_index=all_words.index(colum_word)
#         print("r",row_word)
#         print("c",colum_word)
#         print('row index',row_index)
#         print('colum index',col_index)
        print("***********************")
        data_matrix[row_index,col_index]=total_count
        print(data_matrix)
        
        
        
        
        
        
                    
                
                    
            
        


row word abc
colum_word def
['abc', 'def', 'ijk', 'pqr']
match_position [0]
count 1
temp_count 1
-------------------------------------
row word abc
colum_word def
['lmn', 'pqr', 'xyz', 'abc', 'def', 'pqr', 'abc']
match_position [3, 6]
count 1
temp_count 2
count 1
temp_count 3
-------------------------------------
total count 3
***********************
[[0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
row word abc
colum_word ijk
['abc', 'def', 'ijk', 'pqr']
match_position [0]
count 1
temp_count 1
-------------------------------------
***********************
[[0. 3. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
***********************
[[0. 3. 1. 0. 0. 0. 0. 0.]
 [0

## multo threded implementation 

In [ ]:
window_size=2
count=0
total_count=0
# for row_word in tqdm(two_k_words):
def parelle_co_occurance(row_word):
    print(row_word)
    for colum_word in two_k_words:
        total_count=0
        temp_count=0
        if row_word == colum_word:
            continue
        else :

            for sentence in X_tr["essay_plus_title"]:
                count=0

    #                 for word in range(0,len(sentence.split())):

                if (row_word in sentence) and (colum_word in sentence):
    #                     print("row word",row_word)
    #                     print("colum_word",colum_word)

                    split_sentence=sentence.split()
    #                         row_pos=split_sentence.index(row_word)
    #                     print(split_sentence)
                    match_pos=[n for n,x in enumerate(split_sentence) if x==row_word]
    #                     print("match_position",match_pos)
                    for row_pos in match_pos:
                        found_index_pos=[n for n,x in enumerate(split_sentence) if x==colum_word]
                        distance_from_word=(np.absolute(row_pos-np.array(found_index_pos))<=window_size)
                        count=sum(distance_from_word.flatten())
    #                         print("count",count)
                        temp_count=temp_count+count
    #                         print("temp_count",temp_count)
    #                     print("-------------------------------------")

        total_count=total_count+temp_count
    #         if (row_word in sentence) and (colum_word in sentence): 
    # #             print("total count",total_count)

        row_index=two_k_words.index(row_word)
        col_index=two_k_words.index(colum_word)

    #         print("***********************")
        data_matrix[row_index,col_index]=total_count
        if row_word==two_k_words[-1]:
                with open("co-occurance", 'wb') as f:
                    np.save(f, data_matrix)
        
        
    #         print(data_matrix)
with concurrent.futures.ThreadPoolExecutor() as executor:

    result=[executor.submit(parelle_co_occurance,row_word) for row_word in two_k_words]

In [61]:
"ABC DEF IJK PQR","PQR KLM OPQ","LMN PQR XYZ ABC DEF PQR ABC"

('ABC DEF IJK PQR', 'PQR KLM OPQ', 'LMN PQR XYZ ABC DEF PQR ABC')

In [62]:
data_matrix

array([[0., 3., 1., 0., 0., 0., 3., 1.],
       [3., 0., 1., 0., 0., 0., 2., 1.],
       [1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0.],
       [3., 2., 1., 1., 1., 1., 0., 1.],
       [1., 1., 0., 0., 1., 0., 1., 0.]])